export const cardConfig = {
  good: [
    {
      id: "coins10",
      count: 2,
      title: "Получить 10 монет",
      description: "Получи 10 монет.",
      effect: { type: "coins", amount: 10 },
    },
    {
      id: "forward10",
      count: 2,
      title: "Продвинуться на 10 шагов вперед",
      description: "Продвинься на 10 шагов вперед.",
      effect: { type: "move", steps: 10 },
    },
    {
      id: "steal5",
      count: 2,
      title: "Забери 5 монет у игрока с наибольшим количеством монет",
      description: "Забери 5 монет у игрока с наибольшим количеством монет.",
      effect: { type: "steal-richest", amount: 5 },
    },
    {
      id: "extra-turn",
      count: 2,
      title: "Сделай еще один ход",
      description: "Сделай еще один ход.",
      effect: { type: "extra-turn" },
    },
    {
      id: "free-shop-card",
      count: 2,
      title: "Тяни карту Лавка Джо бесплатно",
      description: "Тяни карту Лавка Джо бесплатно.",
      effect: { type: "draw-free-shop" },
    },
    {
      id: "buy-shop-card",
      count: 2,
      title: "Можешь заплатить 5 монет игроку и забрать его карту Лавка Джо",
      description: "Можешь заплатить 5 монет любому игроку и забрать у него любую карту Лавка Джо. Если у тебя не хватает монет или у противников нет Лавок Джо, получи 5 монет",
      effect: { type: "buy-shop-card-from-player", cost: 5 },
    },
    {
      id: "choose-player-back-roll",
      count: 2,
      title: "Выбери игрока, он делает ход назад используя все свои кубики и бонусы передвижения",
      description: "Выбери игрока, он делает ход назад используя все свои кубики и бонусы передвижения.",
      effect: { type: "choose-player-back-roll" },
    },
    {
      id: "next-battle-minus3",
      count: 2,
      title: "Сглаз",
      description: "Отдай эту карту любому игроку. В следующем бою он получает -3 к силе, затем сбрасывает эту карту.",
      effect: { type: "give-next-battle-penalty", amount: -3 },
    },
    {
      id: "fountain-coin",
      count: 2,
      title: "Монетка из фонтана",
      description: "Получи 8 монет. Если у тебя меньше всех монет, получи 15.",
      effect: { type: "coins-if-poorest", amount: 8, poorestAmount: 15 },
    },
    {
      id: "path-sign",
      count: 2,
      title: "Путевой знак",
      description: "Выбери: идти вперед на 5 или назад на 5. После перемещения назад сработает поле.",
      effect: { type: "choose-forward-or-back", steps: 5 },
    },
  ],
  bad: [
    {
      id: "lose10",
      count: 2,
      title: "Потерять 10 монет",
      description: "Потеряй 10 монет.",
      effect: { type: "coins", amount: -10 },
    },
    {
      id: "back10",
      count: 2,
      title: "Отойти на 10 шагов назад",
      description: "Отойди на 10 шагов назад.",
      effect: { type: "move", steps: -10 },
    },
    {
      id: "give5",
      count: 2,
      title: "Отдай 5 монет игроку с наименьшим количеством монет",
      description: "Отдай 5 монет игроку с наименьшим количеством монет.",
      effect: { type: "give-poorest", amount: 5 },
    },
  ],
  tadam: [
    {
      id: "green-forward",
      count: 2,
      title: "Зеленые поля двигают на 5 клеток вперед",
      description: "Зеленые поля двигают на 5 клеток вперед.",
      effect: { type: "green-field", mode: "move", steps: 5 },
    },
    {
      id: "red-back",
      count: 2,
      title: "Красные поля двигают на 5 клеток назад",
      description: "Красные поля двигают на 5 клеток назад.",
      effect: { type: "red-field", mode: "move", steps: -5 },
    },
    {
      id: "green-good",
      count: 2,
      title: 'Зеленые поля дают карту "Хорошо"',
      description: "Зеленые поля дают карту Хорошо.",
      effect: { type: "green-field", mode: "draw", deck: "good" },
    },
    {
      id: "red-bad",
      count: 2,
      title: 'Красные поля дают карту "Плохо"',
      description: "Красные поля дают карту Плохо.",
      effect: { type: "red-field", mode: "draw", deck: "bad" },
    },
    {
      id: "jump-steal",
      count: 2,
      title: "Перепрыгивая игрока, забери у него 3 монеты",
      description: "Перепрыгивая игрока, забери у него 3 монеты.",
      effect: { type: "jump-steal", amount: 3 },
    },
    {
      id: "land-steal",
      count: 2,
      title: "Если остановился на клетке с другим игроком, забери у него 10 монет",
      description: "Если остановился на клетке с другим игроком, забери у него 10 монет.",
      effect: { type: "land-steal", amount: 10 },
    },
    {
      id: "monster-hunt",
      count: 2,
      title: "Охота на монстра",
      description: "За победу над монстром игрок получает 15 монет.",
      effect: { type: "monster-win-coins", amount: 15 },
    },
  ],
  event: [
    {
      id: "race",
      count: 2,
      title: "Гонка",
      description: "Брось 1 кубик и прибавь бонус шагов. 8 и больше: получи 20 монет. 5-7: получи 10 монет. 4 и меньше: получи 5 монет.",
      effect: { type: "event-race" },
    },
    {
      id: "free-step",
      count: 2,
      title: "Вольный шаг",
      description: "Брось 1 кубик и прибавь бонус шагов. Можешь пройти от 0 до результата клеток вперед.",
      effect: { type: "event-free-step" },
    },
    {
      id: "unity",
      count: 2,
      title: "Сплочение",
      description: "Все игроки вместе сражаются с монстром силой 6 за каждого игрока. Победа: всем +10 монет, лучший удар получает еще +10. Поражение: все теряют 5 монет.",
      effect: { type: "event-unity" },
    },
    {
      id: "justice",
      count: 2,
      title: "Справедливость",
      description: "Первый игрок по маршруту идет на 10 клеток назад, последний игрок идет на 10 клеток вперед, остальные получают 5 монет.",
      effect: { type: "event-justice" },
    },
    {
      id: "balance",
      count: 2,
      title: "Равновесие",
      description: "Самый богатый игрок отдает 10 монет самому бедному игроку.",
      effect: { type: "event-balance", amount: 10 },
    },
    {
      id: "generous-rain",
      count: 2,
      title: "Щедрый дождь",
      description: "Все игроки без монет получают 20 монет. Если монеты есть у всех, все получают 5 монет",
      effect: { type: "event-generous-rain", amount: 20 },
    },
    {
      id: "portal-swap",
      count: 2,
      title: "Портальный обмен",
      description: "Выбери любого другого игрока и поменяйся с ним местами.",
      effect: { type: "event-portal-swap" },
    },
    {
      id: "magic-wallet",
      count: 1,
      title: "Волшебный кошель",
      description: "Последний игрок по маршруту получает артефакт. В начале своего хода владелец получает 5 монет. Если другой игрок обгоняет владельца, артефакт переходит к нему.",
      icon: "./assets/icons/artifact_magic_wallet_512.png",
      effect: { type: "event-magic-wallet" },
    },
    {
      id: "monster-rage",
      count: 2,
      title: "Ярость монстров",
      description: "Все монстры получают +1 к силе. Эффект складывается с другими копиями.",
      effect: { type: "event-monster-rage" },
    },
  ],
  shop: [
    {
      id: "step-plus",
      count: 2,
      title: "+1 к шагам",
      shortTitle: "+1 к шагам",
      description: "+1 к шагам каждый раз, когда двигаешься с помощью кубиков.",
      effect: { type: "passive-step-bonus", steps: 1 },
    },
    {
      id: "battle-plus",
      count: 2,
      title: "+1 к силе",
      shortTitle: "+1 к силе",
      description: "+1 к силе только в битвах.",
      effect: { type: "passive-battle-bonus", amount: 1 },
    },
    {
      id: "coin-plus",
      count: 2,
      title: "Когда получаешь монеты, получай на 2 больше",
      shortTitle: "+2 к монетам",
      description: "Когда получаешь монеты, получай на 2 больше.",
      effect: { type: "passive-coin-bonus", amount: 2 },
    },
    {
      id: "extra-die",
      count: 2,
      title: "Перед ходом можешь заплатить 5 монет и кинуть на 1 кубик больше",
      shortTitle: "+1 кубик за 5",
      description: "Перед броском кубиков можешь заплатить 5 монет и кинуть на 1 кубик больше.",
      effect: { type: "optional-extra-die", cost: 5, dice: 1 },
    },
  ],
};
