export const cardConfig = {
  good: [
    {
      id: "coins10",
      count: 2,
      title: "Звонкая находка",
      description: "Получи 10 монет",
      effect: { type: "coins", amount: 10 },
    },
    {
      id: "forward10",
      count: 2,
      title: "Попутный ветер",
      description: "Продвинься на 10 шагов вперед",
      effect: { type: "move", steps: 10 },
    },
    {
      id: "steal5",
      count: 2,
      title: "Ловкая кража",
      description: "Выбери игрока, забери у него 5 монет",
      effect: { type: "steal-chosen-player", amount: 5 },
    },
    {
      id: "extra-turn",
      count: 2,
      title: "Второе дыхание",
      description: "Сделай еще один ход",
      effect: { type: "extra-turn" },
    },
    {
      id: "free-shop-card",
      count: 2,
      title: "Купон Джо",
      description: "Тяни карту Лавка Джо бесплатно",
      effect: { type: "draw-free-shop" },
    },
    {
      id: "buy-shop-card",
      count: 2,
      title: "Торговый перехват",
      description: "Можешь заплатить 5 монет любому игроку и забрать у него любую карту Лавка Джо. Если у тебя не хватает монет или у противников нет Лавок Джо, получи 5 монет",
      effect: { type: "buy-shop-card-from-player", cost: 5 },
    },
    {
      id: "choose-player-back-roll",
      count: 2,
      title: "Обратный ход",
      description: "Выбери игрока, он делает ход назад используя все свои кубики и бонусы передвижения",
      effect: { type: "choose-player-back-roll" },
    },
    {
      id: "next-battle-minus3",
      count: 2,
      title: "Сглаз",
      description: "Отдай эту карту любому игроку. В следующем бою он получает -3 к силе, затем сбрасывает эту карту",
      effect: { type: "give-next-battle-penalty", amount: -3 },
    },
    {
      id: "next-bad-extra-draw",
      count: 2,
      title: "Двойное Плохо",
      description: "Отдай эту карту любому игроку. В следующий раз, когда он берет карту Плохо, он берет ещё одну",
      effect: { type: "give-next-bad-extra-draw" },
    },
    {
      id: "fountain-coin",
      count: 2,
      title: "Монетка из фонтана",
      description: "Получи 8 монет. Если у тебя меньше всех монет, получи 15",
      effect: { type: "coins-if-poorest", amount: 8, poorestAmount: 15 },
    },
    {
      id: "path-sign",
      count: 2,
      title: "Путевой знак",
      description: "Выбери: идти вперед на 5 или назад на 5. После перемещения назад сработает поле",
      effect: { type: "choose-forward-or-back", steps: 5 },
    },
    {
      id: "field-shield",
      count: 2,
      title: "Защитный знак",
      description: "Оставь эту карту себе. Когда остановился на клетке, можешь не применять её эффект, а сбросить эту карту",
      effect: { type: "field-shield" },
    },
    {
      id: "bad-gift",
      count: 2,
      title: "Плохой подарок",
      description: "Выбери игрока, он берет карту Плохо",
      effect: { type: "bad-gift" },
    },
    {
      id: "green-path",
      count: 2,
      title: "Зеленая тропа",
      description: "Передвинься вперед до ближайшего зеленого поля",
      effect: { type: "green-path" },
    },
    {
      id: "second-chance",
      count: 2,
      title: "Второй шанс",
      description: "Оставь эту карту себе. При проигрыше в битве с монстром можешь сбросить эту карту и проатаковать ещё раз",
      effect: { type: "second-chance" },
    },
    {
      id: "strength-potion",
      count: 2,
      title: "Зелье силы",
      description: "Оставь эту карту себе. В битве с монстром можешь сбросить эту карту и получить +3 к силе",
      effect: { type: "strength-potion", amount: 3 },
    },
    {
      id: "speed-potion",
      count: 2,
      title: "Зелье скорости",
      description: "Оставь эту карту себе. Можешь сбросить в начале хода и получить +5 к шагам на этот ход",
      effect: { type: "speed-potion", steps: 5 },
    },
    {
      id: "dice-control",
      count: 2,
      title: "Контроль кубика",
      description: "Оставь эту карту себе. После броска кубиков можешь поменять значение на одном кубике на любое другое и сбросить эту карту",
      effect: { type: "dice-control" },
    },
    {
      id: "backward-reversal",
      count: 2,
      title: "Разворот",
      description: "Оставь эту карту себе. Когда двигаешься назад, можешь сбросить эту карту и вместо этого передвинуться на столько же шагов вперед",
      effect: { type: "backward-reversal" },
    },
    {
      id: "coin-tribute",
      count: 2,
      title: "Сбор монет",
      description: "Все игроки отдают тебе по 3 монеты (5 при игре вдвоем)",
      effect: { type: "coin-tribute", amount: 3, twoPlayerAmount: 5 },
    },
  ],
  bad: [
    {
      id: "lose10",
      count: 2,
      title: "Дырявый кошель",
      description: "Потеряй 10 монет",
      effect: { type: "coins", amount: -10 },
    },
    {
      id: "back10",
      count: 2,
      title: "Откат назад",
      description: "Отойди на 10 шагов назад",
      effect: { type: "move", steps: -10 },
    },
    {
      id: "give5",
      count: 2,
      title: "Вынужденная щедрость",
      description: "Выбери игрока и отдай ему 5 монет",
      effect: { type: "give-chosen-player", amount: 5 },
    },
    {
      id: "joe-debt",
      count: 2,
      title: "Долги Джо",
      description: "Потеряй 2 монеты за каждую свою Лавку Джо",
      effect: { type: "shop-debt", amount: 2 },
    },
    {
      id: "back-to-red",
      count: 2,
      title: "Красная дорожка",
      description: "Отодвинься назад, до ближайшего красного поля. Эффект поля срабатывает",
      effect: { type: "back-to-nearest-red" },
    },
    {
      id: "small-scare",
      count: 2,
      title: "Легкий испуг",
      description: "Легкий испуг - ничего не происходит",
      effect: { type: "nothing" },
    },
    {
      id: "discard-shop",
      count: 2,
      title: "Потерянная покупка",
      description: "Сбрось одну карту Лавка Джо",
      effect: { type: "discard-owned-shop" },
    },
    {
      id: "back-to-player",
      count: 2,
      title: "Назад к сопернику",
      description: "Отойди назад до ближайшего игрока. Если ты последний, потеряй 5 монет",
      effect: { type: "back-to-nearest-player", amount: -5 },
    },
    {
      id: "others-gain5",
      count: 2,
      title: "Щедрость не туда",
      description: "Все игроки, кроме тебя, получают 5 монет",
      effect: { type: "others-coins", amount: 5 },
    },
    {
      id: "others-shop-offer",
      count: 2,
      title: "Чужая распродажа",
      description: "Все игроки, кроме тебя, тащат карту Лавка Джо и могут купить её за 5 монет",
      effect: { type: "others-shop-offer", cost: 5 },
    },
    {
      id: "leaders-back5",
      count: 2,
      title: "Откат лидеров",
      description: "Все игроки, кроме последнего, делают 5 шагов назад",
      effect: { type: "leaders-back", steps: -5 },
    },
    {
      id: "poorest-steals-shop",
      count: 2,
      title: "Бедняцкий налет",
      description: "Игрок с наименьшим количеством монет забирает у тебя карту Лавка Джо по своему выбору",
      effect: { type: "poorest-steals-shop" },
    },
    {
      id: "bad-die-choice",
      count: 2,
      title: "Кубик неприятностей",
      description: "Брось кубик. 1-2: отойди на 8 шагов назад. 3-4: потеряй 8 монет. 5-6: выбери игрока, он решает, какой из этих двух штрафов ты получишь",
      effect: { type: "bad-die-choice", amount: -8, steps: -8 },
    },
    {
      id: "self-monster-minus3",
      count: 2,
      title: "Дрожь перед монстром",
      description: "Оставь эту карту себе. В следующей битве с монстром получи -3 к силе и сбрось эту карту",
      effect: { type: "self-monster-minus3", amount: -3 },
    },
    {
      id: "skip-next-good",
      count: 2,
      title: "Сломанная удача",
      description: "Оставь эту карту себе. Вместо того чтобы в следующий раз тащить карту Хорошо, сбрось эту карту",
      effect: { type: "skip-next-good" },
    },
    {
      id: "next-turn-pay-or-skip",
      count: 2,
      title: "Тяжелый выбор",
      description: "Оставь эту карту себе. В начале следующего хода выбери: заплатить 15 монет или пропустить ход. Затем сбрось эту карту",
      effect: { type: "next-turn-pay-or-skip", cost: 15 },
    },
    {
      id: "monster-sixes-to-ones",
      count: 2,
      title: "Проклятые шестерки",
      description: "Оставь эту карту себе. В следующей битве с монстром все выброшенные 6 превращаются в 1. После боя сбрось эту карту",
      effect: { type: "monster-sixes-to-ones" },
    },
    {
      id: "flip-shop-down",
      count: 2,
      title: "Закрытая лавка",
      description: "Переверни 2 свои карты Лавка Джо лицом вниз. При посещении клетки Лавка Джо можешь выкупать перевернутые карты по 5 монет за каждую",
      effect: { type: "flip-shop-down", count: 2, cost: 5 },
    },
    {
      id: "block-next-coins",
      count: 2,
      title: "Пустые карманы",
      description: "Оставь эту карту себе. В следующий раз, когда ты должен получить монеты, вместо этого сбрось эту карту",
      effect: { type: "block-next-coins" },
    },
    {
      id: "monster-rematch",
      count: 2,
      title: "Реванш монстра",
      description: "Оставь эту карту себе. В битве с монстром, если ты победил, сбрось эту карту и сразись ещё раз. Получи награду только за вторую победу",
      effect: { type: "monster-rematch" },
    },
  ],
  tadam: [
    {
      id: "green-forward",
      count: 2,
      title: "Зеленый попутчик",
      description: "Зеленые поля двигают на 5 клеток вперед",
      effect: { type: "green-field", mode: "move", steps: 5 },
    },
    {
      id: "red-back",
      count: 2,
      title: "Красный откат",
      description: "Красные поля двигают на 5 клеток назад",
      effect: { type: "red-field", mode: "move", steps: -5 },
    },
    {
      id: "green-good",
      count: 2,
      title: "Зеленая удача",
      description: "Зеленые поля дают карту Хорошо",
      effect: { type: "green-field", mode: "draw", deck: "good" },
    },
    {
      id: "red-bad",
      count: 2,
      title: "Красная беда",
      description: "Красные поля дают карту Плохо",
      effect: { type: "red-field", mode: "draw", deck: "bad" },
    },
    {
      id: "jump-steal",
      count: 2,
      title: "Плата за обгон",
      description: "Перепрыгивая игроков, забери у каждого по 3 монеты",
      effect: { type: "jump-steal", amount: 3 },
    },
    {
      id: "land-steal",
      count: 2,
      title: "Тесная клетка",
      description: "Если остановился на клетке с другим игроком, забери у него 10 монет",
      effect: { type: "land-steal", amount: 10 },
    },
    {
      id: "monster-hunt",
      count: 2,
      title: "Охота на монстра",
      description: "За победу над монстром игрок получает 10 монет",
      effect: { type: "monster-win-coins", amount: 10 },
    },
    {
      id: "same-cell-duel",
      count: 2,
      title: "Дуэль на клетке",
      description: "Если остановился на одной клетке с игроком начинается битва. Эффект клетки срабатывает после битвы. Победитель забирает у проигравшего 10 монет или Лавку Джо на выбор",
      effect: { type: "same-cell-duel", amount: 10 },
    },
    {
      id: "last-good-start",
      count: 2,
      title: "Поддержка отстающего",
      description: "Последний игрок тащит карту Хорошо в начале своего хода",
      effect: { type: "last-good-start", deck: "good" },
    },
    {
      id: "poorest-start-coins",
      count: 2,
      title: "Монеты бедняку",
      description: "Игрок с наименьшим количеством монет в начале хода получает 3 монеты",
      effect: { type: "poorest-start-coins", amount: 3 },
    },
    {
      id: "last-step-plus",
      count: 2,
      title: "Фора последнему",
      description: "Последний игрок получает +5 к шагам",
      effect: { type: "last-step-plus", steps: 5 },
    },
    {
      id: "shop-discount",
      count: 2,
      title: "Скидки у Джо",
      description: "Карты Лавки Джо стоят на 2 монеты дешевле",
      effect: { type: "shop-discount", amount: -2 },
    },
    {
      id: "shop-surcharge",
      count: 2,
      title: "Жадность Джо",
      description: "Карты Лавки Джо стоят на 2 монеты дороже",
      effect: { type: "shop-surcharge", amount: 2 },
    },
    {
      id: "portal-bad",
      count: 2,
      title: "Опасный портал",
      description: "После перемещения через портал игрок берет карту Плохо",
      effect: { type: "portal-bad", deck: "bad" },
    },
    {
      id: "green-extra-coins",
      count: 2,
      title: "Зеленая прибавка",
      description: "Зеленые поля дают дополнительно 3 монеты",
      effect: { type: "green-extra-coins", amount: 3 },
    },
    {
      id: "red-extra-loss",
      count: 2,
      title: "Красный штраф",
      description: "Красные поля отнимают дополнительно 3 монеты",
      effect: { type: "red-extra-loss", amount: 3 },
    },
    {
      id: "good-cashout",
      count: 2,
      title: "Обмен удачи",
      description: "Когда игрок тянет карту Хорошо, он может применить её как обычно или сбросить и получить 8 монет",
      effect: { type: "good-cashout", amount: 8, deck: "good" },
    },
    {
      id: "bad-consolation",
      count: 2,
      title: "Утешение после беды",
      description: "После разыгрывания карты Плохо игрок получает 5 монет",
      effect: { type: "bad-consolation", amount: 5, deck: "bad" },
    },
    {
      id: "monster-bribe",
      count: 2,
      title: "Подкуп монстра",
      description: "Перед битвой с монстром другие игроки могут заплатить 3 монеты: монстр +1 к силе",
      effect: { type: "monster-bribe", amount: 1, cost: 3 },
    },
    {
      id: "rich-weakness",
      count: 2,
      title: "Бремя богатства",
      description: "Если у игрока 20 монет и больше, он получает -2 к силе",
      effect: { type: "rich-weakness", amount: -2 },
    },
  ],
  event: [
    {
      id: "race",
      count: 2,
      title: "Гонка",
      description: "Брось 1 кубик и прибавь бонус шагов. 8 и больше: получи 20 монет. 5-7: получи 10 монет. 4 и меньше: получи 5 монет",
      effect: { type: "event-race" },
    },
    {
      id: "free-step",
      count: 2,
      title: "Вольный шаг",
      description: "Брось 1 кубик и прибавь бонус шагов. Можешь пройти от 0 до результата клеток вперед",
      effect: { type: "event-free-step" },
    },
    {
      id: "unity",
      count: 2,
      title: "Сплочение",
      description: "Общий бой с монстром. При победе все игроки получают 10 монет, при проигрыше все теряют 5 монет",
      effect: { type: "event-unity" },
    },
    {
      id: "justice",
      count: 2,
      title: "Справедливость",
      description: "Первый игрок по маршруту идет на 10 клеток назад, последний игрок идет на 10 клеток вперед, остальные получают 5 монет",
      effect: { type: "event-justice" },
    },
    {
      id: "balance",
      count: 2,
      title: "Равновесие",
      description: "Самый богатый игрок отдает 10 монет самому бедному игроку",
      effect: { type: "event-balance", amount: 10 },
    },
    {
      id: "generous-rain",
      count: 2,
      title: "Щедрый дождь",
      description: "Все игроки без монет получают 20 монет. Если монеты есть у всех, все получают 5 монет",
      effect: { type: "event-generous-rain", amount: 20 },
    },
    {
      id: "portal-swap",
      count: 2,
      title: "Портальный обмен",
      description: "Поменяйся местами с любым игроком. Эффекты полей не применяются",
      effect: { type: "event-portal-swap" },
    },
    {
      id: "magic-wallet",
      count: 1,
      title: "Волшебный кошель",
      description: "Последний игрок по маршруту получает артефакт. В начале своего хода владелец получает 5 монет. Если другой игрок обгоняет владельца, артефакт переходит к нему",
      icon: "./assets/icons/artifact_magic_wallet_512.png",
      effect: { type: "event-magic-wallet" },
    },
    {
      id: "monster-rage",
      count: 2,
      title: "Ярость монстров",
      description: "Все монстры получают +1 к силе. Эффект складывается с другими копиями",
      effect: { type: "event-monster-rage" },
    },
    {
      id: "unity-start",
      count: 2,
      title: "Бой за старт",
      description: "Общий бой с монстром. При победе все игроки получают 10 монет. При проигрыше все игроки отправляются на старт",
      effect: { type: "event-unity-start" },
    },
    {
      id: "shop-redistribution",
      count: 2,
      title: "Перетасовка Лавки",
      description: "Все игроки без карт Лавка Джо берут по 1 карте Лавка Джо. Затем все игроки сбрасывают по 1 карте Лавка Джо. Замешай сброшенные карты и раздай по одной каждому игроку",
      effect: { type: "event-shop-redistribution" },
    },
    {
      id: "fate-draw",
      count: 2,
      title: "Кубик судьбы",
      description: "Брось кубик: 1-2 - тащи карту Плохо, 3-4 - тащи карту Хорошо, 5-6 - тащи карту Лавка Джо",
      effect: { type: "event-fate-draw" },
    },
    {
      id: "triple-tadam",
      count: 2,
      title: "Три ТАДАМ",
      description: "Тащи 3 карты Тадам",
      effect: { type: "event-triple-tadam" },
    },
    {
      id: "mass-good-bad",
      count: 2,
      title: "Общий жребий",
      description: "Брось кубик: 1-3 - все игроки берут по карте Плохо, 4-6 - все игроки берут по карте Хорошо",
      effect: { type: "event-mass-good-bad" },
    },
    {
      id: "golden-markers",
      count: 2,
      title: "Золотые метки",
      description: "Возьми 5 отдельных монет и положи их на любые клетки поля. Игрок, который заканчивает ход на такой клетке, сбрасывает монету с поля и берет 10 монет",
      effect: { type: "event-golden-markers", count: 5, amount: 10 },
    },
    {
      id: "rich-tax",
      count: 2,
      title: "Налог на богатых",
      description: "Все игроки, у которых 20 монет и больше, получают карту Плохо. Остальные игроки получают 5 монет",
      effect: { type: "event-rich-tax", threshold: 20, amount: 5 },
    },
    {
      id: "monster-banner",
      count: 2,
      title: "Знамя монстров",
      description: "Оставь эту карту себе. Пока эта карта в игре, все монстры получают +2 к силе. При победе над монстром возьми карту Хорошо и сбрось эту карту",
      effect: { type: "event-monster-banner", amount: 2 },
    },
    {
      id: "winner-takes-all",
      count: 2,
      title: "Большой приз",
      description: "Все игроки бросают 1 кубик и прибавляют бонусы шагов. Победитель тащит карты: Хорошо, Лавка Джо и Тадам!",
      effect: { type: "event-winner-takes-all" },
    },
    {
      id: "hero-sword",
      count: 1,
      title: "Меч Героя",
      description: "Битва с монстром с силой 6. Брось 1 кубик и прибавь бонусы силы. При победе получи артефакт Меч Героя. При проигрыше ничего не происходит",
      icon: "./assets/icons/artifact_hero_sword_512.png",
      effect: { type: "event-hero-sword", amount: 6, dice: 1, bonusPerSix: 3 },
    },
    {
      id: "anti-bad",
      count: 1,
      title: "Анти-Плохо",
      description: "Игрок с наименьшим количеством монет может отдать 2 Лавки Джо и получить артефакт Анти-Плохо",
      icon: "./assets/icons/artifact_anti_bad_512.png",
      effect: { type: "event-anti-bad", amount: 5, cost: 2 },
    },
  ],
  shop: [
    {
      id: "battle-plus",
      count: 8,
      title: "Тренировочный меч",
      shortTitle: "+1 к силе",
      description: "+1 к силе",
      effect: { type: "passive-battle-bonus", amount: 1 },
    },
    {
      id: "step-plus",
      count: 8,
      title: "Быстрые сапоги",
      shortTitle: "+2 к шагам",
      description: "+2 к шагам",
      effect: { type: "passive-step-bonus", steps: 2 },
    },
    {
      id: "green-fields-plus5",
      count: 6,
      title: "Зеленый бонус",
      shortTitle: "Зеленое +5",
      description: "Зеленые поля дают ещё +5 монет",
      effect: { type: "green-fields-plus5", amount: 5 },
    },
    {
      id: "monster-strength-plus3",
      count: 4,
      title: "Боевой эликсир",
      shortTitle: "+3 к монстру",
      description: "Во время боя с монстром можешь заплатить 5 монет и получить +3 силы на этот бой",
      effect: { type: "monster-strength-plus3", amount: 3, cost: 5 },
    },
    {
      id: "pre-roll-step-plus5",
      count: 4,
      title: "Дорожный рывок",
      shortTitle: "+5 шагов за 5",
      description: "Перед броском кубиков можешь заплатить 5 монет и получить +5 шагов на этот ход",
      effect: { type: "pre-roll-step-plus5", steps: 5, cost: 5 },
    },
    {
      id: "monster-bribe-plus1",
      count: 3,
      title: "Темная взятка",
      shortTitle: "Подкуп +1",
      description: "Когда кто-то бьется с монстром, до его бросков кубиков, можешь заплатить 3 монеты и увеличить силу монстра на 1 на этот бой. Можно делать неограниченное количество раз за бой",
      effect: { type: "monster-bribe-plus1", amount: 1, cost: 3 },
    },
    {
      id: "duplicate-dice-reward",
      count: 3,
      title: "Дубль на удачу",
      shortTitle: "Дубль: 5",
      description: "Если во время хода хотя бы на двух кубиках выпало одно число, выбери: получить 5 монет или сделать 5 шагов вперед",
      effect: { type: "duplicate-dice-reward", amount: 5, steps: 5 },
    },
    {
      id: "tadam-income",
      count: 3,
      title: "Эхо ТАДАМ!",
      shortTitle: "Тадам +3",
      description: "Каждый раз, когда кто-то разыгрывает карту Тадам!, получи 3 монеты",
      effect: { type: "tadam-income", amount: 3 },
    },
    {
      id: "shop-choice-3-cost-3",
      count: 3,
      title: "Привилегия Джо",
      shortTitle: "3 карты за 3",
      description: "Во время покупок карт Лавка Джо выбирай из 3 карт и плати только 3 монеты",
      effect: { type: "shop-choice-3-cost-3", cost: 3, amount: 3 },
    },
    {
      id: "shop-unlimited-buy",
      count: 3,
      title: "Безлимит Джо",
      shortTitle: "Покупай сколько хочешь",
      description: "Можешь покупать любое количество карт Лавка Джо",
      effect: { type: "shop-unlimited-buy" },
    },
    {
      id: "turn-strength-buy",
      count: 3,
      title: "Платная тренировка",
      shortTitle: "10 монет: +1 сила",
      description: "Раз в ход можешь заплатить 10 монет и получить +1 к силе",
      effect: { type: "turn-strength-buy", amount: 1, cost: 10 },
    },
    {
      id: "turn-steps-buy",
      count: 3,
      title: "Платный марш",
      shortTitle: "10 монет: +2 шага",
      description: "Раз в ход можешь заплатить 10 монет и получить +2 к шагам",
      effect: { type: "turn-steps-buy", steps: 2, cost: 10 },
    },
    {
      id: "start-strength",
      count: 3,
      title: "Домашний старт",
      shortTitle: "Старт: +1 сила",
      description: "Каждый раз возвращаясь на поле Старт получи +1 к силе",
      effect: { type: "start-strength", amount: 1 },
    },
    {
      id: "reroll-one-move-die",
      count: 3,
      title: "Переброс маршрута",
      shortTitle: "Переброс за 3",
      description: "Раз в ход после броска кубиков можешь заплатить 3 монеты и перебросить один кубик. Если ты бросаешь кубики не в свой ход, ты не можешь использовать эту карту",
      effect: { type: "reroll-one-move-die", cost: 3 },
    },
    {
      id: "move-one-farther",
      count: 3,
      title: "Еще шажок",
      shortTitle: "+1 шаг за 3",
      description: "После броска кубиков для движения, можешь заплатить 3 монеты и пройти на 1 шаг дальше",
      effect: { type: "move-one-farther", steps: 1, cost: 3 },
    },
  ],
};
