export const cardConfig = {
  good: [
    {
      id: "coins10",
      count: 1,
      title: "Получить 10 монет",
      description: "Получи 10 монет.",
      effect: { type: "coins", amount: 10 },
    },
    {
      id: "forward10",
      count: 1,
      title: "Продвинуться на 10 шагов вперед",
      description: "Продвинься на 10 шагов вперед.",
      effect: { type: "move", steps: 10 },
    },
    {
      id: "steal5",
      count: 1,
      title: "Забери 5 монет у игрока с наибольшим количеством монет",
      description: "Забери 5 монет у игрока с наибольшим количеством монет.",
      effect: { type: "steal-richest", amount: 5 },
    },
    {
      id: "extra-turn",
      count: 1,
      title: "Сделай еще один ход",
      description: "Сделай еще один ход.",
      effect: { type: "extra-turn" },
    },
    {
      id: "free-shop-card",
      count: 1,
      title: "Тяни карту Лавка Джо бесплатно",
      description: "Тяни карту Лавка Джо бесплатно.",
      effect: { type: "draw-free-shop" },
    },
    {
      id: "buy-shop-card",
      count: 1,
      title: "Можешь заплатить 5 монет игроку и забрать его карту Лавка Джо",
      description: "Можешь заплатить 5 монет игроку и забрать его карту Лавка Джо.",
      effect: { type: "buy-shop-card-from-player", cost: 5 },
    },
  ],
  bad: [
    {
      id: "lose10",
      title: "Потерять 10 монет",
      description: "Потеряй 10 монет.",
      effect: { type: "coins", amount: -10 },
    },
    {
      id: "back10",
      title: "Отойти на 10 шагов назад",
      description: "Отойди на 10 шагов назад.",
      effect: { type: "move", steps: -10 },
    },
    {
      id: "give5",
      title: "Отдай 5 монет игроку с наименьшим количеством монет",
      description: "Отдай 5 монет игроку с наименьшим количеством монет.",
      effect: { type: "give-poorest", amount: 5 },
    },
  ],
  tadam: [
    {
      id: "green-forward",
      title: "Зеленые поля двигают на 5 клеток вперед",
      description: "Зеленые поля двигают на 5 клеток вперед.",
      effect: { type: "green-field", mode: "move", steps: 5 },
    },
    {
      id: "red-back",
      title: "Красные поля двигают на 5 клеток назад",
      description: "Красные поля двигают на 5 клеток назад.",
      effect: { type: "red-field", mode: "move", steps: -5 },
    },
    {
      id: "green-good",
      title: 'Зеленые поля дают карту "Хорошо"',
      description: "Зеленые поля дают карту Хорошо.",
      effect: { type: "green-field", mode: "draw", deck: "good" },
    },
    {
      id: "red-bad",
      title: 'Красные поля дают карту "Плохо"',
      description: "Красные поля дают карту Плохо.",
      effect: { type: "red-field", mode: "draw", deck: "bad" },
    },
    {
      id: "jump-steal",
      title: "Перепрыгивая игрока, забери у него 3 монеты",
      description: "Перепрыгивая игрока, забери у него 3 монеты.",
      effect: { type: "jump-steal", amount: 3 },
    },
    {
      id: "land-steal",
      title: "Если остановился на клетке с другим игроком, забери у него 10 монет",
      description: "Если остановился на клетке с другим игроком, забери у него 10 монет.",
      effect: { type: "land-steal", amount: 10 },
    },
  ],
  shop: [
    {
      id: "step-plus",
      title: "+1 к броску кубика",
      shortTitle: "+1 к броску",
      description: "+1 к броску кубика.",
      effect: { type: "passive-step-bonus", steps: 1 },
    },
    {
      id: "coin-plus",
      title: "Когда получаешь монеты, получай на 2 больше",
      shortTitle: "+2 к монетам",
      description: "Когда получаешь монеты, получай на 2 больше.",
      effect: { type: "passive-coin-bonus", amount: 2 },
    },
    {
      id: "extra-die",
      title: "Перед ходом можешь заплатить 5 монет и кинуть на 1 кубик больше",
      shortTitle: "+1 кубик за 5",
      description: "Перед ходом можешь заплатить 5 монет и кинуть на 1 кубик больше.",
      effect: { type: "optional-extra-die", cost: 5, dice: 1 },
    },
  ],
};
